FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copier le code du front
COPY front/ front/

# Installer les dépendances Flask + requests
RUN pip install --upgrade pip && pip install -r front/requirements.txt

EXPOSE 5000

CMD ["python", "front/app.py"]
